### ISSUE TITLE
Betelgeuse not detecting device

### ISSUE THREAD

**Issue by dinouse** [23Aaron/Betelguese#12] opened 2021-05-24 17:09 UTC
I have iPhone SE 2016 after jailbreaking and as soon i want to odysseyra1n the tools doesnt seems to detecting my device but checkra1n do detecting my device. 

Bigsur 11.3.1
iPhone SE 2016 iOS 14.0

**Comment by StateOfInstinct** [comment] 2021-05-26 19:17
Same with me 

Big Sur 11.4
iPhone 7 iOS 14.4

**Comment by 23Aaron** [comment] 2021-05-26 19:43
Have you taken the usual troubleshooting steps? Unplugging and replugging the device in etc.

**Comment by StateOfInstinct** [comment] 2021-05-27 01:54
Yes, I have

**Comment by ZydePunk77** [comment] 2021-06-07 01:14
Same. Will not recognize iPhone 7, but will recognize my X that’s jailbroken with Taurine

**Comment by 23Aaron** [comment] 2021-06-17 19:35
@ZydePunk77 Are both devices plugged in?

**Comment by ZydePunk77** [comment] 2021-06-18 00:19
> @ZydePunk77 Are both devices plugged in?

No. They were not. It recognizes the X....but acts as if nothing is connected when I plug in my iPhone 7. 

I’ve never had them both plugged in simultaneously.

**Comment by kirb** [comment] 2023-07-06 02:11
Closing due to time elapsed since the issue was opened. If the issue is still occurring, please feel free to reopen or make a new issue.

**Closed as completed by kirb** 2023-07-06 02:11 UTC
Labels: bug
